# Generated by Django 5.0 on 2023-12-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app11', '0002_rename_curse_student_course_alter_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='music_instrument',
            field=models.CharField(choices=[('Фортепиано', 'Фортепиано'), ('Гитара', 'Гитара'), ('Скрипка', 'Скрипка')], max_length=255),
        ),
    ]
